### ISSUE TITLE
دعم أمكانية الوصول Accessibility support

### ISSUE THREAD

**Issue by MesterPerfect** [muslimpack/Quran#1]
السَلام عليكم ورحمة الله وبركاته 
بارك الله مجهوداتك أخي الكريم وجعلها الله في ميزان حسناتك 
لقد قمت بتجربة التطبيق وهو رائع جدا 
ولكنني لا أستطيع قراءة الآيات بستخدام قارئ الشاشة الخاص بالمكفوفين 
هل يمكنك تطبيق إرشادات Flutter المتعلقة بإمكانية الوصول هنا 
وجزيت خيرا 

https://docs.flutter.dev/ui/accessibility-and-localization/accessibility

**Comment by HasanEltantawy** [comment]
جزاك الله خيرا على مراجعتك أخي الكريم
سنعمل على حل هذه المشكلة في التحديثات المقبلة إن شاء الله
نفع الله بك
