### ISSUE TITLE
دعم ميزة material you

### ISSUE THREAD

**Issue by CaptechOmar** [muslimpack/Quran#3]
نتمني دعم ميزة material you كما في تطبيق حصن المسلم لتتناسب مع الوان النظام بشكل عام ويكون هناك تناسق بين باقي التطبيقات المستخدمة

**Comment by 7Eltantawy** [comment]
التطبيق حاليا لا نية لجعل الواجهة يمكن تغيير الإضاءة الخاصة بها على عكس صفحات المصحف 
- وضع نهاري
- وضع ليلي
- وضع أصفر مع التحكم في تشبع اللون
