### ISSUE TITLE
امكانية التغيير بين طبعات المصحف

### ISSUE THREAD

**Issue by CaptechOmar** [muslimpack/Quran#4]
لو امكن اضافة امكانية التغيير بين أنواع طبعات المصحف المستخدمة كما في تطبيق قرآن اندرويد كمصحف المدينة لعام 1440هـ ومصحف التجويد إلى آخره

**Comment by 7Eltantawy** [comment]
هذه الخاصية بالفعل على خطتنا لكن المتاح حاليا هي طبعة المدينة
