### ISSUE TITLE
ميزة عرض صفحتين متجاورتين في الوضع الأفقي لا تعمل

### ISSUE THREAD

**Issue by CaptechOmar** [muslimpack/Quran#6]
رغم تفعيل الميزة فإنها لا تعمل في الوضع الأفقي ولا يوجد فرق بين تفعيل الميزة أو إلغاء تفعيلها في الوضع الأفقي

**Comment by 7Eltantawy** [comment]
تأكد من تفعيل الخاصية من الإعدادات
الخاصية عند تفعيلها تعمل في الأجهزة عند عرض معين
وهي خاصة بأجهزة سطح المكتب وأجهزة التابلت
